### ISSUE TITLE
K-means or DBSCAN to measure amount of coffee from a picture?

### ISSUE THREAD

**Issue by Eivinddh** [inf219-mocca/MOCCAPI#29]
https://scikit-learn.org/stable/modules/clustering.html#dbscan

**Comment by sondr3** [comment]
Maybe just use curves and make it very bright black on white?

![gray](https://user-images.githubusercontent.com/2280539/54924332-6ee1bb80-4f0c-11e9-9405-aa6e0e08a31c.jpg)
